<?php

/**
 * Implements hook_mail().
 */
function ckan_admin_mail($key, &$message, $params) {
  switch ($key) {
    case 'addReuse':
      $message['from'] = "contact@bpm-conseil.com";//\Drupal::config('system.site')->get('mail');
      //$message['headers']['Content-Type'] = 'charset=UTF-8;';
      $message['subject'] = $params['subject'];
      $message['body'] = $params['message'];
      $message['options'] = []; error_log(json_encode($message));
     /* if (isset($params['options']) && !empty($params['options'])) {
        foreach ($params['options'] as $key => $value) {
          $message['options'][$key] = $value;
        }
      }*/
      break;
  }
}

/**
 * Implements hook_mail_alter().
 */
function another_module_mail_alter(&$message) {
  switch ($message['key']) {
    case 'addReuse':
      //$message['body'][] = t('Additionnal message');
      break;
  }
}