<?php

/**
 * Implements hook_mail().
 */
function ckan_admin_mail($key, &$message, $params) {
  switch ($key) {
    case 'addReuse':
      $message['from'] = "contact@bpm-conseil.com";//\Drupal::config('system.site')->get('mail');
      //$message['headers']['Content-Type'] = 'charset=UTF-8;';
      $message['subject'] = $params['subject'];
      $message['body'] = $params['message'];
      $message['options'] = []; error_log(json_encode($message));
     /* if (isset($params['options']) && !empty($params['options'])) {
        foreach ($params['options'] as $key => $value) {
          $message['options'][$key] = $value;
        }
      }*/
      break;
  }
}

/**
 * Implements hook_theme().
 */
function ckan_admin_theme($existing, $type, $theme, $path) {
  return [
    'visualizations_template' => [
      'variables' => ['selectOptions' => NULL, 'selectedName' => NULL, 'selectedType' => NULL, 'visualizations' => NULL, 'error' => NULL]
    ]
  ];
}

/**
 * Implements hook_mail_alter().
 */
function another_module_mail_alter(&$message) {
  switch ($message['key']) {
    case 'addReuse':
      //$message['body'][] = t('Additionnal message');
      break;
  }
}

/**
 * Implements hook_page_attachments().
 * @param array $attachments
 */
function ckan_admin_page_attachments(array &$attachments) {
    //add here any conditions if you need to limit the pages

    $attachments['#attached']['library'][] = 'ckan_admin/routing';
    $attachments['#attached']['library'][] = 'ckan_admin/tools';
}